= Installing on Ubuntu desktop image

* General > Advanced: Shared Clipboard Bidirectional
* Network > Bridged Adapter

Devices > Install Guest Additions
```
sudo apt-get update
sudo apt-get install -y dkms build-essential linux-headers-generic linux-headers-$(uname -r)
sudo mount /dev/cdrom /media/cdrom
sudo /media/cdrom/VBoxLinuxAdditions.run
```

= Installing on Ubuntu server image

Before the final step of running `VBoxLinuxAdditions.run`, either:
 
 * Install xserver (you can then use a tool like https://sourceforge.net/projects/xming/[Xming] (XLaunch) with http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html[PuTTY]): `sudo apt-get install xserver-xorg`
 * Run the final step without X11 support:
   `sudo /media/cdrom/VBoxLinuxAdditions.run --nox11`

To copy and paste into the console running in the VirtualBox window you may want to install GPM.

*Update*: Unfortunately the GPM clipboard does not sync with the X11 clipboard, so copy and paste still does not work. One of the solutions here may work: http://superuser.com/questions/451039

= Shared folders

Attempting to access the shared folders will give the error `Permission denied`
```
sudo adduser your_username vboxsf
sudo reboot
```

= Errors

http://superuser.com/a/768845[VT-x/AMD-V hardware acceleration is not available on your system]

VT-x/AMD-V support gets disabled for VirtualBox if you have Hyper-V installed. Disable Hyper-V from an elevated command prompt by typing:

`dism.exe /Online /Disable-Feature:Microsoft-Hyper-V`


= Networking

When creating a virtual machine, the network adapter used seems to correspond to whether you are using Wi-fi or cable at that time?

If you later switch then you can get network errors at boot time and have to manually reconfigure network settings.

E.g. LOCAL VM won't run on wi-fi: "a start job is running for raise network interfaces" - Adding a second network adapter (wi-fi card with a different MAC address) prevents the error and allows boot - but because this card is not set up in the OS I don't get an IP address. https://ubuntuforums.org/showthread.php?t=2323253

* Host-Only: The VM will be assigned one IP, but it's only accessible by the box VM is running on. No other computers can access it.
* NAT: Just like your home network with a wireless router, the VM will be assigned in a separate subnet, like 192.168.6.1 is your host computer, and VM is 192.168.6.3, then your VM can access outside network like your host, but no outside access to your VM directly, it's protected.
* Bridged: Your VM will be in the same network as your host, if your host IP is 172.16.120.45 then your VM will be like 172.16.120.50. It can be accessed by all computers in your host network.

http://www.virtualbox.org/manual/ch06.html#networkingmodes[More info]... NAT Network may actually provide a workable solution without having to use bridged adapters communicating with the real hardware.

If you get the error "no NAT Network name is currently specified" then you have to create a NAT Network in the main VirtualBox application first (File > Preferences > Network (NAT Networks) > Add New NAT Network).
